## whitelist
branches:
  only:
    - gateway-travis
    - minimal-gateway-travis
    - pkg-only-gateway-travis
    - workstation-travis
    - minimal-workstation-travis
    - pkg-only-workstation-travis

## Not working due to device-mapper missing in Travis CI VMs.
## See also:
## - https://www.whonix.org/wiki/Dev/Continuous_Integration
## - https://github.com/travis-ci/travis-ci/issues/1493
#script: sudo -E ./whonix_build [...]

## Try building a physically isolated machine instead.
script:
  - sudo -E "./packages/whonix-developer-meta-files/debug-steps/travis"
