## whitelist
branches:
  only:
    - gateway-travis
    - minimal-gateway-travis
    - pkg-only-gateway-travis
    - workstation-travis
    - minimal-workstation-travis
    - pkg-only-workstation-travis

## Not working due to device-mapper missing in Travis CI VMs.
## See also:
## - https://www.whonix.org/wiki/Dev/Continuous_Integration
## - https://github.com/travis-ci/travis-ci/issues/1493
#script: sudo -E ./whonix_build_both

## Try building a physically isolated machine instead.
script:
  - cd help-steps ; ls -la ; WHONIX_BUILD_PARSED="1" VMNAME="internalrun" source variables
  - cd .. ; ls -la ; git clone https://github.com/Whonix/whonix-developer-meta-files
  - sudo -E "$whonix_dev_meta_files_folder/debug-steps/travis"
