# whitelist
branches:
  only:
    - travis

## Not working due to device-matter missing in Travis CI VMs.
## See also:
## - https://www.whonix.org/wiki/Dev/Continuous_Integration
## - https://github.com/travis-ci/travis-ci/issues/1493
#script: sudo -E ./whonix_build_both

## Try building a physically isolated Whonix-Gateway instead.
script: sudo -E ./whonix_build --tor-gateway --bare-metal --build
