# whitelist
branches:
  only:
    - travis

## Not working due to device-matter missing in Travis CI VMs.
#script: sudo -E ./whonix_build_both

## Try building a physically isolated Whonix-Gateway instead.
script: sudo -E ./whonix_build --tor-gateway --bare-metal --build
