## whitelist
branches:
  only:
    - travis-gateway
    - travis-gateway-minimal
    - travis-gateway-pkg-only
    - travis-workstation
    - travis-workstation-minimal
    - travis-workstation-pkg-only

## Not working due to device-mapper missing in Travis CI VMs.
## See also:
## - https://www.whonix.org/wiki/Dev/Continuous_Integration
## - https://github.com/travis-ci/travis-ci/issues/1493
#script: sudo -E ./whonix_build [...]

## Try building a physically isolated machine instead.
script:
  - sudo -E "./packages/whonix-developer-meta-files/debug-steps/travis"
